export const QUOTES = [
  {
    id: 1,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    authorFirstName: "Mahatma",
    authorSecondName: "Gandhi",
    genre: "life",
  },
  {
    id: 2,
    img: "./images/personalities/Nietzsche.jpg",
    quote: "That which does not kill us makes us stronger.",
    authorFirstName: "Friedrich",
    authorSecondName: "Nietzsche",
    genre: "life",
  },
  {
    id: 3,
    img: "./images/personalities/bernard-baruch.jpg",
    quote:
      "Be who you are and say what you feel, because those who mind don’t matter and those who matter don’t mind.",
    authorFirstName: "Bernard",
    authorSecondName: "M. Baruch",
    genre: "life",
  },
  {
    id: 4,
    img: "./images/personalities/virginia-satir.jpg",
    quote: "We must not allow other people’s limited perceptions to define us.",
    authorFirstName: "Virginia",
    authorSecondName: "Satir",
    genre: "life",
  },
  {
    id: 5,
    img: "./images/personalities/President_Roosevelt.jpg",
    quote: "Do what you can, with what you have, where you are.",
    authorFirstName: "Theodore",
    authorSecondName: "Roosevelt",
    genre: "life",
  },
  {
    id: 6,
    img: "./images/personalities/oscar-wilde.jpg",
    quote: "Be yourself; everyone else is already taken.",
    authorFirstName: "Oscar",
    authorSecondName: "Wilde",
    genre: "life",
  },
  {
    id: 7,
    img: "./images/personalities/william-shakespeare.jpg",
    quote: "This above all: to thine own self be true.",
    authorFirstName: "William",
    authorSecondName: "Shakespeare",
    genre: "life",
  },
  {
    id: 8,
    img: "./images/personalities/Napoleon_Hill.jpg",
    quote: "If you cannot do great things, do small things in a great way.",
    authorFirstName: "Napoleon",
    authorSecondName: "Hill",
    genre: "life",
  },
  {
    id: 9,
    img: "./images/personalities/Milton_Berle.jpg",
    quote: "If opportunity doesn’t knock, build a door.",
    authorFirstName: "Milton",
    authorSecondName: "Berle",
    genre: "wisdom",
  },
  {
    id: 10,
    img: "./images/personalities/Plato.jpg",
    quote:
      "Wise men speak because they have something to say; fools because they have to say something.",
    authorFirstName: "Plato",
    authorSecondName: " ",
    genre: "wisdom",
  },
  {
    id: 11,
    img: "./images/personalities/albert-einstein.jpg",
    quote: "Strive not to be a success, but rather to be of value.",
    authorFirstName: "Albert",
    authorSecondName: "Einstein",
    genre: "wisdom",
  },
  {
    id: 12,
    img: "./images/personalities/jim-rohn.jpg",
    quote:
      "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.",
    authorFirstName: "John",
    authorSecondName: "Wooden",
    genre: "life",
  },
  {
    id: 13,
    img: "./images/personalities/mark-twain.jpg",
    quote:
      "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
    authorFirstName: "Mark",
    authorSecondName: "Twain",
    genre: "wisdom",
  },
  {
    id: 14,
    img: "./images/personalities/thomas-Edison.png",
    quote: "I haven’t failed. I’ve just found 10,000 ways that won’t work.",
    authorFirstName: "Thomas",
    authorSecondName: "Edison",
    genre: "life",
  },
  {
    id: 15,
    img: "./images/personalities/lao-tzu.jpg",
    quote: "A journey of a thousand leagues begins beneath one’s feet.",
    authorFirstName: "Lao",
    authorSecondName: "Tzu",
    genre: "wisdom",
  },
  {
    id: 16,
    img: "./images/personalities/john-Wooden.jpg",
    quote: "Do not let what you cannot do interfere with what you can do.",
    authorFirstName: "John",
    authorSecondName: "Wooden",
    genre: "life",
  },
  {
    id: 17,
    img: "./images/personalities/maya_angelou.jpg",
    quote:
      "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
    authorFirstName: "Maya",
    authorSecondName: "Angelou",
    genre: "life",
  },
  {
    id: 18,
    img: "./images/personalities/jim-rohn.jpg",
    quote: "Either you run the day, or the day runs you",
    authorFirstName: "Jim",
    authorSecondName: "Rohn",
    genre: "life",
  },
  {
    id: 19,
    img: "./images/personalities/anais-Nin.jpg",
    quote: "Life shrinks or expands in proportion to one’s courage.",
    authorFirstName: "Anais",
    authorSecondName: "Nin",
    genre: "life",
  },
  {
    id: 20,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "You must be the change you wish to see in the world.",
    authorFirstName: "Mahatma",
    authorSecondName: "Gandhi",
    genre: "life",
  },
  {
    id: 21,
    img: "./images/personalities/ralph-waldo.jpg",
    quote: "What you do speaks so loudly that I cannot hear what you say.",
    authorFirstName: "Ralph",
    authorSecondName: "Waldo Emerson",
    genre: "wisdom",
  },
  {
    id: 22,
    img: "./images/personalities/jimmy-johnson.jpg",
    quote:
      "The difference between ordinary and extraordinary is that little extra.",
    authorFirstName: "Jimmy",
    authorSecondName: "Johnson",
    genre: "life",
  },
  {
    id: 23,
    img: "./images/personalities/charles-kettering.jpg",
    quote: "Believe and act as if it were impossible to fail.",
    authorFirstName: "Charles",
    authorSecondName: "Kettering",
    genre: "life",
  },
  {
    id: 24,
    img: "./images/personalities/alan-kay.jpg",
    quote: "The best way to predict the future is to invent it.",
    authorFirstName: "Alan",
    authorSecondName: "Kay",
    genre: "wisdom",
  },
  {
    id: 25,
    img: "./images/personalities/rabbi-hillel.jpg",
    quote:
      "If I am not for myself, who is for me? And if I am only for myself, what am I? And if not now, when?",
    authorFirstName: "Rabbi",
    authorSecondName: "Hillel",
    genre: "wisdom",
  },
  {
    id: 26,
    img: "./images/personalities/confucius.jpg",
    quote: "Everything has beauty, but not everyone can see.",
    authorFirstName: "Confucius",
    authorSecondName: " ",
    genre: "life",
  },
  {
    id: 27,
    img: "./images/personalities/President_Roosevelt.jpg",
    quote: "Believe you can and you’re halfway there.",
    authorFirstName: "Theodore",
    authorSecondName: "Roosevelt",
    genre: "life",
  },
  {
    id: 28,
    img: "./images/personalities/ann.jpg",
    quote:
      "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
    authorFirstName: "Anne",
    authorSecondName: "Frank",
    genre: "greatness",
  },
  {
    id: 29,
    img: "./images/personalities/albert-einstein.jpg",
    quote:
      "Imagination is everything. It is the preview of life’s coming attractions.",
    authorFirstName: "Albert",
    authorSecondName: "Einstein",
    genre: "wisdom",
  },
  {
    id: 30,
    img: "./images/personalities/norman.jpg",
    quote: "Change your thoughts and you change your world.",
    authorFirstName: "Norman",
    authorSecondName: "Vincent",
    genre: "wisdom",
  },
  {
    id: 31,
    img: "./images/personalities/dalai.jpg",
    quote:
      "Happiness is not something ready made. It comes from your own actions.",
    authorFirstName: "Dalai",
    authorSecondName: "Lama",
    genre: "happiness",
  },
  {
    id: 32,
    img: "./images/personalities/roy.jpg",
    quote: "Remember that happiness is a way of travel, not a destination.",
    authorFirstName: "Roy",
    authorSecondName: "M. Goodman",
    genre: "happiness",
  },
  {
    id: 33,
    img: "./images/personalities/les.jpg",
    quote:
      "Too many of us are not living our dreams because we are living our fears.",
    authorFirstName: "Les",
    authorSecondName: "Brown",
    genre: "happiness",
  },
  {
    id: 34,
    img: "./images/personalities/booker.jpg",
    quote: "If you want to lift yourself up, lift up someone else.",
    authorFirstName: "Booker",
    authorSecondName: "T. Washington",
    genre: "wisdom",
  },
  {
    id: 35,
    img: "./images/personalities/wayne.jpg",
    quote: "You miss 100% of the shots you don’t take.",
    authorFirstName: "Wayne",
    authorSecondName: "Gretzky",
    genre: "wisdom",
  },
  {
    id: 36,
    img: "./images/personalities/george.jpg",
    quote: "It is never too late to be what you might have been.",
    authorFirstName: "George",
    authorSecondName: "Eliot",
    genre: "wisdom",
  },
  {
    id: 37,
    img: "./images/personalities/albert-einstein.jpg",
    quote: "A person who never made a mistake never tried anything new.",
    authorFirstName: "Albert",
    authorSecondName: "Einstein",
    genre: "wisdom",
  },
  {
    id: 38,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "The person who says it cannot be done should not interrupt the person who is doing it.",
    authorFirstName: "Chinese",
    authorSecondName: "Proverb",
    genre: "wisdom",
  },
  {
    id: 39,
    img: "./images/personalities/eleanor.jpg",
    quote:
      "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    authorFirstName: "Eleanor",
    authorSecondName: "Roosevelt",
    genre: "wisdom",
  },
  {
    id: 40,
    img: "./images/personalities/mae.jpg",
    quote: "You only live once, but if you do it right, once is enough.",
    authorFirstName: "Mae",
    authorSecondName: "West",
    genre: "life",
  },
  {
    id: 41,
    img: "./images/personalities/mark-twain.jpg",
    quote: "If you tell the truth, you don’t have to remember anything.",
    authorFirstName: "Mark",
    authorSecondName: "Twain",
    genre: "wisdom",
  },
  {
    id: 42,
    img: "./images/personalities/helen.jpg",
    quote:
      "The only thing worse than being blind is having sight but no vision.",
    authorFirstName: "Helen",
    authorSecondName: "Keller",
    genre: "wisdom",
  },
  {
    id: 43,
    img: "./images/personalities/President_Roosevelt.jpg",
    quote: "The only thing we have to fear is fear itself.",
    authorFirstName: "Franklin",
    authorSecondName: "D. Roosevelt",
    genre: "fear",
  },
  {
    id: 44,
    img: "./images/personalities/oscar-wilde.jpg",
    quote:
      "To live is the rarest thing in the world. Most people exist, that is all.",
    authorFirstName: "Oscar",
    authorSecondName: "Wilde",
    genre: "life",
  },
  {
    id: 45,
    img: "./images/personalities/martin.jpg",
    quote:
      "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
    authorFirstName: "Martin",
    authorSecondName: "Luther King, Jr.",
    genre: "love",
  },
  {
    id: 46,
    img: "./images/personalities/oprah.jpg",
    quote:
      "If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.",
    authorFirstName: "Oprah",
    authorSecondName: "Winfrey",
    genre: "life",
  },
  {
    id: 47,
    img: "./images/personalities/eleanor.jpg",
    quote: "Remember no one can make you feel inferior without your consent.",
    authorFirstName: "Eleanor",
    authorSecondName: "Roosevelt",
    genre: "wisdom",
  },
  {
    id: 48,
    img: "./images/personalities/ralph-waldo.jpg",
    quote:
      "For every minute you are angry you lose sixty seconds of happiness.",
    authorFirstName: "Ralph",
    authorSecondName: "Waldo Emerson",
    genre: "happiness",
  },
  {
    id: 49,
    img: "./images/personalities/lao-tzu.jpg",
    quote:
      "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
    authorFirstName: "Lao",
    authorSecondName: "Tzu",
    genre: "love",
  },
  {
    id: 50,
    img: "./images/personalities/edith.jpg",
    quote:
      "There are two ways of spreading light: to be the candle or the mirror that reflects it.",
    authorFirstName: "Edith",
    authorSecondName: "Wharton",
    genre: "wisdom",
  },
  {
    id: 51,
    img: "./images/personalities/colin.jpg",
    quote:
      "The road to success and the road to failure are almost exactly the same.",
    authorFirstName: "Colin",
    authorSecondName: "R. Davis",
    genre: "life",
  },
  {
    id: 52,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Motivation is a fire from within. If someone else tries to light that fire under you, chances are it will burn very briefly.",
    authorFirstName: "Stephen",
    authorSecondName: "R. Covey",
    genre: "wisodm",
  },
  {
    id: 53,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "In three words I can sum up everything I’ve learned about life: It goes on.",
    authorFirstName: "Robert",
    authorSecondName: "Frost",
    genre: "life",
  },
  {
    id: 54,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Self-reverence, self-knowledge, self control — these three alone lead to power.",
    authorFirstName: "Alfred,",
    authorSecondName: "Lord Tennyson",
    genre: "wisdom",
  },
  {
    id: 55,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending.",
    authorFirstName: "Carl",
    authorSecondName: "Bard",
    genre: "wisdom",
  },
  {
    id: 56,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young. The greatest thing in life is to keep your mind young.",
    authorFirstName: "Henry",
    authorSecondName: "Ford",
    genre: "life",
  },
  {
    id: 57,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "He who angers you conquers you.",
    authorFirstName: "Elizabeth",
    authorSecondName: "Kenny",
    genre: "anger",
  },
  {
    id: 58,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "Beauty, without expression, tires.",
    authorFirstName: "Ralph",
    authorSecondName: "Waldo Emerson",
    genre: "beauty",
  },
  {
    id: 59,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "The secret of business is to know something that nobody else knows.",
    authorFirstName: "Aristotle",
    authorSecondName: "Onassis",
    genre: "business",
  },
  {
    id: 60,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
    authorFirstName: "Oprah",
    authorSecondName: "Winfrey",
    genre: "life",
  },
  {
    id: 61,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "We cannot always build the future of our youth, but we can build our youth for the future.",
    authorFirstName: "Franklin",
    authorSecondName: "D. Roosevelt",
    genre: "life",
  },
  {
    id: 62,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "It takes courage to grow up and turn out to be who you really are.",
    authorFirstName: "E.E.",
    authorSecondName: "Cummings",
    genre: "life",
  },
  {
    id: 63,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "In this world nothing can be said to be certain, except death and taxes.",
    authorFirstName: "Benjamin",
    authorSecondName: "Franklin",
    genre: "wisdom",
  },
  {
    id: 64,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
    authorFirstName: "Aristotle",
    authorSecondName: " ",
    genre: "wisdom",
  },
  {
    id: 65,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "A happy family is but an earlier heaven.",
    authorFirstName: " George",
    authorSecondName: "Bernard Shaw",
    genre: "family",
  },
  {
    id: 66,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Don’t walk in front of me, I may not follow. Don’t walk behind me, I may not lead. Walk beside me and be my friend.",
    authorFirstName: "Albert",
    authorSecondName: "Camus",
    genre: "friendship",
  },
  {
    id: 67,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Courage doesn’t always roar. Sometimes courage is the little voice at the end of the day that says ‘I’ll try again tomorrow.",
    authorFirstName: "Mary",
    authorSecondName: "Anne Radmacher",
    genre: "resillience",
  },
  {
    id: 68,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Education is like a double-edged sword. It may be turned to dangerous uses if it is not properly handled.",
    authorFirstName: "Wu",
    authorSecondName: "Ting-Fang",
    genre: "education",
  },
  {
    id: 69,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Walking with a friend in the dark is better than walking alone in the light.",
    authorFirstName: "Helen",
    authorSecondName: "Keller",
    genre: "friendship",
  },
  {
    id: 70,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "Happiness is not a goal; it is a by-product.",
    authorFirstName: "Eleanor",
    authorSecondName: "Roosevelt",
    genre: "happiness",
  },
  {
    id: 71,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "Always forgive your enemies; nothing annoys them so much.",
    authorFirstName: "Oscar",
    authorSecondName: "Wilde",
    genre: "forgiveness",
  },
  {
    id: 72,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "As a well-spent day brings happy sleep, so a life well spent brings happy death.",
    authorFirstName: "Leonardo",
    authorSecondName: "da Vinci",
    genre: "happiness",
  },
  {
    id: 73,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "Children are our most valuable resource.",
    authorFirstName: "Herbert",
    authorSecondName: "Hoover",
  },
  {
    id: 74,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "Love is, above all else, the gift of oneself.",
    authorFirstName: "Jean",
    authorSecondName: "Anouilh",
    genre: "love",
  },
  {
    id: 75,
    img: "./images/personalities/laotzu.jpg",
    quote: "Music in the soul can be heard by the universe.",
    authorFirstName: "Lao",
    authorSecondName: "Tzu",
    genre: "music",
  },
  {
    id: 76,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "Peace begins with a smile.",
    authorFirstName: "Mother",
    authorSecondName: "Teresa",
    genre: "wisdom",
  },
  {
    id: 77,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Success is liking yourself, liking what you do, and liking how you do it.",
    authorFirstName: "Maya",
    authorSecondName: "Angelou",
    genre: "wisdom",
  },
  {
    id: 78,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "The only true wisdom is knowing that you know nothing.",
    authorFirstName: "Socrates",
    authorSecondName: " ",
    genre: "wisdom",
  },
  {
    id: 79,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Courage is what it takes to stand up and speak. Courage is also what it takes to sit down and listen.",
    authorFirstName: "Winston",
    authorSecondName: "Churchill",
    genre: "courage",
  },
  {
    id: 80,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "A friend is someone who knows all about you and still loves you.",
    authorFirstName: "Elbert",
    authorSecondName: "Hubbard",
    genre: "friendship",
  },
  {
    id: 81,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "Never leave that till tomorrow which you can do today.",
    authorFirstName: "Benjamin",
    authorSecondName: "Franklin",
    genre: "wisdom",
  },
  {
    id: 82,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "If you don’t make mistakes, you’re not working on hard enough problems.",
    authorFirstName: "Frank",
    authorSecondName: "Wilczek",
    genre: "wisdom",
  },
  {
    id: 83,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "We must learn to live together as brothers or perish together as fools.",
    authorFirstName: "Martin",
    authorSecondName: "Luther King, Jr.",
    genre: "wisdom",
  },
  {
    id: 84,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Life is like a camera. Just focus on what’s important, capture the good times, develop from the negatives, and if things don’t work out, just take another shot.",
    authorFirstName: "Unknown",
    authorSecondName: " ",
    genre: "life",
  },
  {
    id: 85,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "When you judge another, you do not define them; you define yourself.",
    authorFirstName: "Wayne",
    authorSecondName: "Dyer",
    genre: "judgement",
  },
  {
    id: 86,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Opportunity is missed by most people because it is dressed in overalls and looks like work.",
    authorFirstName: "Thomas",
    authorSecondName: "Edison",
    genre: "wisdom",
  },
  {
    id: 87,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Love me when I least deserve it, because that’s when I really need it.",
    authorFirstName: "Swedish",
    authorSecondName: "Proverb",
    genre: "love",
  },
  {
    id: 88,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart.",
    authorFirstName: "Helen",
    authorSecondName: "Keller",
    genre: "beauty",
  },
  {
    id: 89,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "If you want to test your memory, try to recall what you were worrying about one year ago today.",
    authorFirstName: "E. Joseph",
    authorSecondName: "Cossman",
    genre: "wisdom",
  },
  {
    id: 90,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "The real opportunity for success lies within the person and not in the job.",
    authorFirstName: "Zig",
    authorSecondName: "Ziglar",
    genre: "wisdom",
  },
  {
    id: 91,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "It takes a great deal of courage to stand up to your enemies, but even more to stand up to your friends.",
    authorFirstName: " J. K.",
    authorSecondName: "Rowling",
    genre: "friendship",
  },
  {
    id: 92,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "Defeat is not bitter unless you swallow it.",
    authorFirstName: "Joe",
    authorSecondName: "Clark",
    genre: "wisdom",
  },
  {
    id: 93,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "A mind is like a parachute. It doesn’t work if it isn’t open.",
    authorFirstName: "Frank",
    authorSecondName: "Zappa",
    genre: "wisdom",
  },
  {
    id: 94,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "The man who removes a mountain begins by carrying away small stones.",
    authorFirstName: "Chinese",
    authorSecondName: "Proverbs",
    genre: "wisdom",
  },
  {
    id: 95,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "When you are totally at peace with yourself, nothing can shake you.",
    authorFirstName: "Deepam",
    authorSecondName: "Chatterjee",
    genre: "life",
  },
  {
    id: 96,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Be a first rate version of yourself, not a second rate version of someone else.",
    authorFirstName: "Judy",
    authorSecondName: "Garland",
    genre: "life",
  },
  {
    id: 97,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "Your worth consists in what you are and not in what you have.",
    authorFirstName: "Thomas",
    authorSecondName: "Edison",
    genre: "life",
  },
  {
    id: 98,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote:
      "Others can stop you temporarily – you are the only one who can do it permanently.",
    authorFirstName: "Zig",
    authorSecondName: "Ziglar",
    genre: "life",
  },
  {
    id: 99,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "Life has no limitations, except the ones you make.",
    authorFirstName: "Les",
    authorSecondName: "Brown",
    genre: "life",
  },
  {
    id: 100,
    img: "./images/personalities/mahatma-gandhi.jpg",
    quote: "Peace comes from within. Do not seek it without.",
    authorFirstName: "Muhammad",
    authorSecondName: "Ali",
    genre: "life",
  },
];

export const IMAGES = [
  {
    id: 1,
    url: "./images/personalities/pexels-alex-andrews-3805983.jpg",
    genre: "universe",
  },
  {
    id: 2,
    url: "./images/personalities/pexels-felix-mittermeier-956981.jpg",
    genre: "universe",
  },
  {
    id: 3,
    url: "./images/personalities/pexels-pixabay-33688.jpg",
    genre: "universe",
  },
];
